[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@uniswap-core/=lib/v2-core/',
    '@uniswap-periphery/=lib/v2-periphery/',
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 1000
gas_reports = ["*"]
[fuzz]
runs = 2000
[rpc_endpoints]
base = "${BASE_RPC_URL}"
[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
